# Generated by Django 6.1 on 2026-08-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس های با ما',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_photo', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان عکس')),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'بارگذاری عکس',
                'verbose_name_plural': 'بارگذاری عکس ها',
            },
        ),
        migrations.CreateModel(
            name='VehicleTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='دسته بندی خودرو')),
            ],
            options={
                'verbose_name': 'دسته بندی خودرو',
                'verbose_name_plural': 'دسته بندی خودروها',
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='عکس اصلی')),
                ('pump_model', models.CharField(max_length=100, verbose_name='مدل پمپ')),
                ('pump_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع پمپ')),
                ('body_material', models.CharField(blank=True, max_length=300, null=True, verbose_name='جنس بدنه پمپ')),
                ('shaft_material', models.CharField(blank=True, max_length=200, null=True, verbose_name='جنس شفت')),
                ('Kind_butterfly', models.CharField(blank=True, max_length=100, null=True, verbose_name='جنس پروانه')),
                ('flow_direction', models.CharField(blank=True, max_length=100, null=True, verbose_name='جهت گردش')),
                ('maximum_pressure', models.CharField(blank=True, max_length=300, null=True, verbose_name='حداکثر فشار بسته')),
                ('Output_flow_rate', models.CharField(blank=True, max_length=400, null=True, verbose_name='دبی خروجی')),
                ('required_distance', models.CharField(blank=True, max_length=150, null=True, verbose_name='دور مورد نیاز پمپ')),
                ('Vacuum_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع خلاء')),
                ('preparation_speed', models.CharField(blank=True, max_length=100, null=True, verbose_name='سرعت آماده سازی پمپ')),
                ('maximum_suction_depth', models.CharField(blank=True, max_length=50, null=True, verbose_name='حداکثر عمق مکش')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('slug', models.SlugField(default='', max_length=400, unique=True, verbose_name='عنوان در url')),
                ('img', models.ManyToManyField(blank=True, null=True, to='mainpage.image', verbose_name='عکس')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.vehicletitle', verbose_name='دسته بندی خودرها')),
            ],
            options={
                'verbose_name': 'پمپ آتش نشانی',
                'verbose_name_plural': 'پمپ های آتش نشانی',
            },
        ),
        migrations.CreateModel(
            name='MunicipalityVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='عکس اصلی')),
                ('uses', models.CharField(blank=True, max_length=400, null=True, verbose_name='موارد استفاده')),
                ('dimension', models.CharField(blank=True, max_length=200, null=True, verbose_name='ابعاد(میلیمتر)(ارتفاع*عرض*طول)')),
                ('chassis', models.CharField(max_length=100, verbose_name='شاسی')),
                ('chassis_english', models.CharField(blank=True, max_length=150, null=True, verbose_name='شاسی به انگلیسی')),
                ('cooling_system', models.TextField(blank=True, null=True, verbose_name='سیستم خنک کننده')),
                ('hydraulic_pump', models.CharField(blank=True, max_length=200, null=True, verbose_name='پمپ هیدرولیک')),
                ('tank', models.CharField(blank=True, max_length=300, null=True, verbose_name='مخزن')),
                ('refuse_tank', models.CharField(blank=True, max_length=300, null=True, verbose_name='مخزن زباله')),
                ('hopper', models.CharField(blank=True, max_length=300, null=True, verbose_name='هاپر')),
                ('been_off_load_mechanism', models.CharField(blank=True, max_length=350, null=True, verbose_name='مکانیزم تخلیه سطل')),
                ('drain_shovel', models.CharField(blank=True, max_length=350, null=True, verbose_name='بیل تخلیه')),
                ('hydraulic_equipment', models.TextField(blank=True, null=True, verbose_name='تجهیزات هیدرولیکی')),
                ('pressing_system', models.CharField(blank=True, max_length=200, null=True, verbose_name='سیستم پرس زباله')),
                ('water_pump', models.CharField(blank=True, max_length=200, null=True, verbose_name='پمپ آب')),
                ('water_tank', models.CharField(blank=True, max_length=500, null=True, verbose_name='مخزن آب')),
                ('cabin', models.TextField(blank=True, null=True, verbose_name='کابین')),
                ('door', models.TextField(blank=True, null=True, verbose_name='درب ها')),
                ('roller_shutter', models.CharField(blank=True, max_length=300, null=True, verbose_name='کرکره ها')),
                ('powder_system', models.TextField(blank=True, null=True, verbose_name='سیستم پودر')),
                ('equipment', models.TextField(verbose_name='تجهیزات')),
                ('slug', models.SlugField(default='', max_length=400, unique=True, verbose_name='عنوان در url')),
                ('img', models.ManyToManyField(blank=True, null=True, to='mainpage.image', verbose_name='عکس')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.vehicletitle', verbose_name='دسته بندی خودرها')),
            ],
            options={
                'verbose_name': 'خودرو خدمات شهری',
                'verbose_name_plural': 'خودرو های خدمات شهری',
            },
        ),
        migrations.CreateModel(
            name='FireFightingVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='عکس اصلی')),
                ('uses', models.CharField(blank=True, max_length=200, null=True, verbose_name='موارد استفاده')),
                ('dimension', models.CharField(blank=True, max_length=200, null=True, verbose_name='ابعاد(میلیمتر)(ارتفاع*عرض*طول)')),
                ('chassis', models.CharField(max_length=100, verbose_name='شاسی')),
                ('chassis_english', models.CharField(blank=True, max_length=150, null=True, verbose_name='شاسی به انگلیسی')),
                ('extinguishing_system', models.TextField(blank=True, null=True, verbose_name='سیستم اطفا')),
                ('water_pump', models.CharField(blank=True, max_length=200, null=True, verbose_name='پمپ آب')),
                ('water_tank', models.CharField(blank=True, max_length=500, null=True, verbose_name='مخزن آب')),
                ('foam_tank', models.CharField(blank=True, max_length=200, null=True, verbose_name='مخزن فوم')),
                ('monitor', models.CharField(blank=True, max_length=500, null=True, verbose_name='مانیتور')),
                ('hose_reel', models.CharField(blank=True, max_length=500, null=True, verbose_name='هوزریل')),
                ('cabin', models.TextField(verbose_name='کابین')),
                ('roller_shutter', models.CharField(blank=True, max_length=300, null=True, verbose_name='کرکره ها')),
                ('powder_system', models.TextField(blank=True, null=True, verbose_name='سیستم پودر')),
                ('equipment', models.TextField(verbose_name='تجهیزات')),
                ('slug', models.SlugField(default='', max_length=400, unique=True, verbose_name='عنوان در url')),
                ('img', models.ManyToManyField(blank=True, null=True, to='mainpage.image', verbose_name='عکس')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.vehicletitle', verbose_name='دسته بندی خودرها')),
            ],
            options={
                'verbose_name': 'خودرو آتش نشانی',
                'verbose_name_plural': 'خودرو های آتش نشانی',
            },
        ),
        migrations.CreateModel(
            name='AmbulanceVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='عکس اصلی')),
                ('chassis', models.CharField(blank=True, max_length=100, null=True, verbose_name='شاسی')),
                ('chassis_english', models.CharField(blank=True, max_length=150, null=True, verbose_name='شاسی به انگلیسی')),
                ('sick_cabin', models.TextField(blank=True, null=True, verbose_name='کابین بیمار')),
                ('electricity_lighting_system', models.TextField(blank=True, null=True, verbose_name='سیستم برق و روشنایی ')),
                ('cooling_heating_system', models.CharField(blank=True, max_length=400, null=True, verbose_name='سیستم سرمایش و گرمایش ')),
                ('ambulance_signs', models.TextField(blank=True, null=True, verbose_name='سیستم آلارم و آژیر و علائم ظاهری آمبولانس')),
                ('medical_equipment', models.TextField(blank=True, null=True, verbose_name='تجهیزات پزشکی')),
                ('slug', models.SlugField(default='', max_length=400, unique=True, verbose_name='عنوان در url')),
                ('img', models.ManyToManyField(blank=True, null=True, to='mainpage.image', verbose_name='عکس')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.vehicletitle', verbose_name='دسته بندی خودرها')),
            ],
            options={
                'verbose_name': 'خودرو آمبولانس',
                'verbose_name_plural': 'خودرهای آمبولانس',
            },
        ),
    ]
