# Generated by Django 6.1 on 2026-08-16 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ambulancevehicle',
            options={'verbose_name': 'خودرو آمبولانس', 'verbose_name_plural': 'خودروهای آمبولانس'},
        ),
        migrations.AddField(
            model_name='ambulancevehicle',
            name='equipment',
            field=models.TextField(default='', verbose_name='تجهیزات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambulancevehicle',
            name='chassis',
            field=models.CharField(default='', max_length=100, verbose_name='شاسی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambulancevehicle',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.vehicletitle', verbose_name='دسته بندی خودروها'),
        ),
        migrations.AlterField(
            model_name='firefightingvehicle',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.vehicletitle', verbose_name='دسته بندی خودروها'),
        ),
        migrations.AlterField(
            model_name='municipalityvehicle',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.vehicletitle', verbose_name='دسته بندی خودروها'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.vehicletitle', verbose_name='دسته بندی خودروها'),
        ),
        migrations.CreateModel(
            name='VehicleSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=200, verbose_name='عنوان مشخصه')),
                ('value', models.TextField(verbose_name='مقدار مشخصه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['firefightingvehicle', 'municipalityvehicle', 'ambulancevehicle', 'pump']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'مشخصه فنی',
                'verbose_name_plural': 'مشخصات فنی',
                'ordering': ['order'],
                'unique_together': {('content_type', 'object_id', 'key')},
            },
        ),
    ]
