# Generated by Django 6.1 on 2026-08-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_remove_ambulancevehicle_ambulance_signs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancevehicle',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات بیشتر درباره خودرو (متن دلخواه)', null=True, verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AddField(
            model_name='firefightingvehicle',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات بیشتر درباره خودرو (متن دلخواه)', null=True, verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AddField(
            model_name='municipalityvehicle',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات بیشتر درباره خودرو (متن دلخواه)', null=True, verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AddField(
            model_name='pump',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات بیشتر درباره خودرو (متن دلخواه)', null=True, verbose_name='توضیحات تکمیلی'),
        ),
    ]
