# Generated by Django 6.1 on 2026-08-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_ambulancevehicle_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancevehicle',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='firefightingvehicle',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='municipalityvehicle',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='image_title',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس اصلی'),
        ),
    ]
